apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - envs
  - postgres.yaml

patchesStrategicMerge:
  - search.yaml
  - web.yaml
  - sync-daemon.yaml
  - web-deployment.yaml

secretGenerator:
  - name: web
    envs:
      - envs/web.env
  - name: search
    envs:
      - envs/search.env
  - name: daemon
    envs:
      - envs/daemon.env
  - name: shared
    envs:
      - envs/shared.env
  - name: scrape
    envs:
      - envs/scrape.env
