apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      containers:
        - name: search
          image: 932829830564.dkr.ecr.us-east-1.amazonaws.com/search:0.0.0
      volumes:
        - name: vol
          hostPath:
            path: /opt/models
