apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /opt/models
