# Generated by Django 3.0.4 on 2020-03-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='first',
            field=models.BooleanField(default=True),
        ),
    ]
