# Generated by Django 3.0.4 on 2020-03-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_author_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='published_at',
            field=models.DateField(),
        ),
    ]
