# Generated by Django 3.0.4 on 2020-03-28 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200328_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first',
        ),
    ]
