# Generated by Django 3.0.4 on 2020-03-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200328_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='citation_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='paper',
            name='latent_topic_score',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='latent_topic_score',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='papers', to='data.Topic'),
        ),
    ]
