# Generated by Django 3.0.4 on 2020-03-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200328_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(default=''),
        ),
    ]
