# Generated by Django 3.0.4 on 2020-03-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_paper_topic_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='citations_last_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='citation_count',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
