# Generated by Django 3.0.4 on 2020-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200329_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
