# Generated by Django 3.0.4 on 2020-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_topic_description_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-citation_count']},
        ),
        migrations.AddField(
            model_name='topic',
            name='icon_path',
            field=models.CharField(default='', max_length=60),
        ),
    ]
