# Generated by Django 3.0.4 on 2020-03-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_paper_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='preview_image',
            field=models.ImageField(default=None, null=True, upload_to='pdf_images'),
        ),
    ]
