# Generated by Django 3.0.4 on 2020-03-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20200329_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='icon_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
