# Generated by Django 3.0.4 on 2020-03-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200329_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Unknown', max_length=300),
        ),
    ]
