# Generated by Django 3.0.5 on 2020-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20200406_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='scholar_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
