# Generated by Django 2.1 on 2020-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_author_scholar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
