# Generated by Django 2.1 on 2020-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_paper_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='last_scrape',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
