# Generated by Django 3.0.4 on 2020-05-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_paper_last_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='split_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='covid_related',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='data.Category'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='published_at',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='version',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='paperhost',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='paperhost',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='data_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='data.DataSource'),
        ),
        migrations.AddField(
            model_name='paper',
            name='data_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='data.DataSource'),
        ),
    ]
