# Generated by Django 3.0.4 on 2020-05-27 11:45
from django.db import migrations, models


def transfer_datasource_values(apps, schema_editor):
    """Transfers all datasource foreign keys to corresponding enum type ID."""
    from data.models import DataSource

    PaperModel = apps.get_model('data', 'Paper')

    for paper in PaperModel.objects.all():
        if paper.data_source.name == 'medbiorxiv-updater':
            paper.data_source_id = DataSource.MEDBIORXIV
        elif paper.data_source.name == 'arxiv-updater':
            paper.data_source_id = DataSource.ARXIV
        else:
            raise Exception(f"Unknown datasource: {paper.data_source_id}")
        paper.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20200507_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='author',
            name='split_name',
        ),
        migrations.RenameModel(
            old_name='DataSource',
            new_name='DataSource_OLD',
        ),
        migrations.AddField(
            model_name='paper',
            name='data_source_id',
            field=models.IntegerField(choices=[(0, 'medbioRxiv'), (1, 'arXiv')], null=True),
        ),
        migrations.RunPython(
            transfer_datasource_values
        ),
        migrations.RemoveField(
            model_name='paper',
            name='data_source',
        ),
        migrations.DeleteModel(
            name='DataSource_OLD'
        )
    ]
