# Generated by Django 3.0.4 on 2020-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0024_auto_20200518_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_state',
            field=models.IntegerField(
                choices=[(0, 'Declined'), (1, 'Data Error'), (2, 'Unknown'), (3, 'Automatically accepted'),
                         (4, 'Verified')], default=2),
        ),
    ]
