# Generated by Django 3.0.4 on 2020-05-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20200527_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='citation_count',
        ),
        migrations.RemoveField(
            model_name='author',
            name='citations_last_update',
        ),
        migrations.RemoveField(
            model_name='author',
            name='scholar_url',
        ),
    ]
