# Generated by Django 3.0.4 on 2020-05-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20200527_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
