# Generated by Django 3.0.4 on 2020-05-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20200527_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_state',
            field=models.IntegerField(choices=[(0, 'Declined'), (2, 'Unknown'), (3, 'Automatically accepted'), (4, 'Verified')], default=2),
        ),
        migrations.AddField(
            model_name='paper',
            name='pubmed_id',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='data_source_value',
            field=models.IntegerField(choices=[(0, 'medbioRxiv'), (1, 'arXiv'), (2, 'pubmed')], null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='data.Journal'),
        ),
    ]
