# Generated by Django 3.0.4 on 2020-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20200528_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='alias',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
