# Generated by Django 3.0.4 on 2020-06-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20200529_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
