# Generated by Django 3.0.4 on 2020-06-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20200602_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredPaper',
            fields=[
                ('doi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ignore_reason', models.TextField(default=None, null=True)),
                ('url', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='data_source_value',
            field=models.IntegerField(choices=[(0, 'medbioRxiv'), (1, 'arXiv'), (2, 'pubmed'), (3, 'elsevier')], null=True),
        ),
    ]
