# Generated by Django 3.0.4 on 2020-06-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20200602_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='latent_topic_score',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='latent_topic_score',
        ),
    ]
