# Generated by Django 3.0.4 on 2020-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200604_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='data_source_value',
            field=models.IntegerField(choices=[(0, 'medbioRxiv'), (1, 'arXiv'), (2, 'pubmed'), (3, 'elsevier')]),
        ),
    ]
