# Generated by Django 3.0.4 on 2020-06-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200603_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
