# Generated by Django 3.0.4 on 2020-06-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='categories',
            field=models.ManyToManyField(related_name='papers', to='data.Category'),
        ),
    ]
