# Generated by Django 3.0.4 on 2020-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_paper_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='model_identifier',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
