# Generated by Django 3.0.4 on 2020-06-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_category_color'),
        ('data', '0031_auto_20200605_1318'),
    ]

    operations = [
    ]
