# Generated by Django 3.0.7 on 2020-06-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20200611_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='count',
        ),
    ]
