# Generated by Django 3.0.7 on 2020-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_geolocation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoNameResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('target_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GeoStopword',
        ),
    ]
