# Generated by Django 3.0.7 on 2020-06-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20200616_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='geonames_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
