# Generated by Django 3.0.7 on 2020-06-24 12:24

from django.db import migrations, models


def delete_geolocations(apps, schema_editor):
    GeoLocation = apps.get_model('data', 'GeoLocation')
    GeoLocationMembership = apps.get_model('data', 'GeoLocationMembership')
    GeoNameResolution = apps.get_model('data', 'GeoNameResolution')

    GeoLocationMembership.objects.all().delete()
    GeoLocation.objects.all().delete()
    GeoNameResolution.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20200616_1547'),
    ]

    operations = [
        migrations.RunPython(delete_geolocations),
    ]
