# Generated by Django 3.0.7 on 2020-06-18 22:38

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20200616_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('comment', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='scrape_hash',
            field=models.CharField(default=None, max_length=22, null=True),
        ),
        migrations.CreateModel(
            name='ScrapeError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'missing data'), (1, 'paper conflict'), (2, 'data error')])),
                ('datapoint', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('hash', models.CharField(db_index=True, max_length=22)),
                ('comment', models.CharField(default=None, max_length=50, null=True)),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Paper')),
            ],
        ),
    ]
