# Generated by Django 3.0.7 on 2020-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_geolocation_geonames_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='geonames_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='geonameresolution',
            name='target_name',
        ),
        migrations.AddField(
            model_name='geonameresolution',
            name='target_geonames_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='location_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geocountry',
            name='alpha_2',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='geonameresolution',
            name='source_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
