# Generated by Django 3.0.7 on 2020-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_auto_20200625_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='alias',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='geolocationmembership',
            name='word',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
