# Generated by Django 3.0.7 on 2020-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20200629_1515'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='geolocationmembership',
            constraint=models.UniqueConstraint(fields=('paper', 'location'), name='Paper and Location'),
        ),
    ]
