# Generated by Django 3.0.7 on 2020-07-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20200705_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
