# Generated by Django 3.0.7 on 2020-07-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20200705_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='manually_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='scrape_hash',
            field=models.CharField(default=None, max_length=22, null=True),
        ),
    ]
