# Generated by Django 3.0.7 on 2020-07-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20200709_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=300)),
                ('keywords', models.TextField()),
                ('overlapping_paper_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='papers', to='data.Topic'),
        ),
    ]
