# Generated by Django 3.0.7 on 2020-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_auto_20200709_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='vectorized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='visualized',
            field=models.BooleanField(default=True),
        ),
    ]
