# Generated by Django 3.0.7 on 2020-07-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20200707_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperhost',
            name='url',
        ),
        migrations.AlterField(
            model_name='paper',
            name='data',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper', to='data.PaperData'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='data.Journal'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='preview_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pdf_images'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pubmed_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='papers', to='data.Topic'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='version',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
