# Generated by Django 3.0.7 on 2020-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20200714_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='vectorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='visualized',
            field=models.BooleanField(default=False),
        ),
    ]
