# Generated by Django 3.0.7 on 2020-07-21 13:48

from django.db import migrations, models
import django.db.models.deletion


def fill_membership_table(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AuthorPaperMembership = apps.get_model('data', 'AuthorPaperMembership')
    Paper = apps.get_model('data', 'Paper')

    for old_membership in Paper.authors.through.objects.all():
        AuthorPaperMembership.objects.create(paper_id=old_membership.paper_id, author_id=old_membership.author_id)


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20200721_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPaperMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Paper')),
            ],
        ),
        migrations.RunPython(fill_membership_table),
    ]
