# Generated by Django 3.0.7 on 2020-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_authorpapermembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(related_name='publications', through='data.AuthorPaperMembership',
                                         to='data.Author'),
        ),
    ]
