# Generated by Django 3.0.7 on 2020-07-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_remove_paper_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltmetricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('score_d', models.FloatField(default=0)),
                ('score_w', models.FloatField(default=0)),
                ('score_1m', models.FloatField(default=0)),
                ('score_3m', models.FloatField(default=0)),
                ('score_6m', models.FloatField(default=0)),
                ('score_y', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='altmetric_data',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper', to='data.AltmetricData'),
        ),
    ]
