# Generated by Django 3.0.7 on 2020-07-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_auto_20200723_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altmetricdata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='paper',
            name='last_altmetric_update',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
