# Generated by Django 3.0.7 on 2021-07-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_auto_20200723_1536'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['published_at'], name='data_paper_publish_6c2ffb_idx'),
        ),
    ]
