# Generated by Django 3.0.7 on 2021-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_auto_20210705_1241'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='altmetricdata',
            index=models.Index(fields=['score'], name='data_altmet_score_72537c_idx'),
        ),
        migrations.AddIndex(
            model_name='altmetricdata',
            index=models.Index(fields=['score_d'], name='data_altmet_score_d_066062_idx'),
        ),
        migrations.AddIndex(
            model_name='altmetricdata',
            index=models.Index(fields=['score_w'], name='data_altmet_score_w_8e3258_idx'),
        ),
        migrations.AddIndex(
            model_name='altmetricdata',
            index=models.Index(fields=['score_1m'], name='data_altmet_score_1_001602_idx'),
        ),
    ]
