# Generated by Django 3.0.7 on 2021-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_auto_20210705_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperdata',
            name='abstract',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
