# Generated by Django 3.0.7 on 2021-07-05 14:17

from django.db import migrations
from django.db import transaction
from django.core.paginator import Paginator


def transfer_abstracts(apps, schema_editor):
    # We can't import the Paper, PaperData model directly as it may be a newer
    Paper = apps.get_model('data', 'Paper')
    PaperData = apps.get_model('data', 'PaperData')

    paginator = Paginator(Paper.objects.all().order_by("-doi"), 500)

    for i in paginator.page_range:
        chunk = paginator.get_page(i).object_list
        with transaction.atomic():
            for paper in chunk:
                if paper.data:
                    data = paper.data
                    data.abstract = paper.abstract
                    data.save()
                else:
                    paper.data = PaperData.objects.create(paper=paper, abstract=paper.abstract)
                paper.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_paperdata_abstract'),
    ]

    operations = [
        migrations.RunPython(transfer_abstracts)
    ]
