# Generated by Django 3.0.7 on 2021-07-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_auto_20210705_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='abstract',
        ),
        migrations.AlterField(
            model_name='paper',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='data.PaperData'),
        ),
    ]
