apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collabovid-base-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - "deployments"
      - "events"
      - "jobs"
    verbs:
      - "create"
      - "get"
      - "list"
      - "delete"
  - apiGroups:
      - ""
      - "metrics.k8s.io"
    resources:
      - "nodes"
      - "pods"
      - "nodes/stats"
    verbs:
      - "watch"
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collabovid-base-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collabovid-base-role
subjects:
  - kind: User
    name: collabovid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collabovid-role-creator
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "clusterroles"
      - "clusterrolebindings"
    verbs:
      - "create"
      - "patch"
      - "get"
      - "watch"
      - "list"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collabovid-role-creator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collabovid-role-creator
subjects:
  - kind: User
    name: collabovid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collabovid-api-service
rules:
  - apiGroups:
      - "apiregistration.k8s.io"
    resources:
      - "apiservices"
    verbs:
      - "create"
      - "get"
      - "patch"
      - "list"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collabovid-api-service-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collabovid-api-service
subjects:
  - kind: User
    name: collabovid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collabovid-authentication
rules:
  - apiGroups:
      - "authentication.k8s.io"
    resources:
      - "tokenreviews"
    verbs:
      - "create"
      - "delete"
  - apiGroups:
    - "authorization.k8s.io"
    resources:
      - "subjectaccessreviews"
    verbs:
      - "create"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collabovid-authentication-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collabovid-authentication
subjects:
  - kind: User
    name: collabovid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collabovid-ingress-role
rules:
  - apiGroups:
      - "traefik.containo.us"
    resources:
      - "ingressroutes"
      - "middlewares"
    verbs:
      - "get"
      - "create"
      - "list"
      - "watch"
      - "delete"
      - "patch"
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "clusterissuers"
      - "certificates/status"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
      - "patch"
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates/status"
    verbs:
      - "get"
      - "update"
  - apiGroups:
    - "networking.k8s.io"
    resources:
      - "ingressclasses"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collabovid-ingress-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collabovid-ingress-role
subjects:
  - kind: User
    name: collabovid

