# Generated by Django 3.0.7 on 2020-07-29 16:50

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchquery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
