# Generated by Django 3.0.4 on 2020-03-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_paper_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(),
        ),
    ]
