# Generated by Django 3.0.4 on 2020-03-30 02:34

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20200329_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('citation_count'), descending=True, nulls_last=True)]},
        ),
    ]
