# Generated by Django 3.0.4 on 2020-04-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_paper_last_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='orcid',
            field=models.TextField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal_doi',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='license',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
