# Generated by Django 3.0.4 on 2020-04-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20200430_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='datasource',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
