# Generated by Django 3.0.4 on 2020-04-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20200421_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='journal_doi',
        ),
    ]
