# Generated by Django 3.0.5 on 2020-04-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20200430_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='scrape_method',
        ),
        migrations.AddField(
            model_name='author',
            name='split_name',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ScrapeMethod',
        ),
        migrations.AddField(
            model_name='author',
            name='data_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='data.DataSource'),
        ),
        migrations.AddField(
            model_name='paper',
            name='data_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='data.DataSource'),
        ),
    ]
