# Generated by Django 3.0.4 on 2020-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20200430_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='published_at',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paperhost',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
