# Generated by Django 3.0.4 on 2020-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20200501_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='paperhost',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
