# Generated by Django 3.0.4 on 2020-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20200501_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='version',
            field=models.CharField(default='1', max_length=40),
        ),
    ]
