# Generated by Django 3.0.4 on 2020-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20200502_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='version',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
