# Generated by Django 3.0.4 on 2020-05-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200502_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='priority',
        ),
    ]
