# Generated by Django 3.0.4 on 2020-05-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_remove_datasource_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pmcid',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pubmed_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
