# Generated by Django 3.0.4 on 2020-05-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_auto_20200504_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
