# Generated by Django 3.0.4 on 2020-05-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20200506_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossrefType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='crossref_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='data.CrossrefType'),
        ),
    ]
