import os

TASK_LOGGING_DB_FLUSH_SECONDS = int(os.getenv("TASK_LOGGING_DB_FLUSH_SECONDS", "20"))
TASK_LAUNCHER_LOCAL = False
SEARCH_MODELS_HOST_PATH = os.getenv('SEARCH_MODELS_HOST_PATH', '/.docker/collabovid-data/models')

TASK_IMAGE_PULL_POLICY = os.getenv("TASK_IMAGE_PULL_POLICY", "Always")
TASK_DELETE_SUCCESSFUL_PODS = False
TASK_DELETE_FAILED_PODS = False
