apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      containers:
        - name: search
          env:
            - name: REGISTRY
              value: ""
            - name: TASK_IMAGE_PULL_POLICY
              value: "Never"