apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: REGISTRY
              value: ""
            - name: TASK_IMAGE_PULL_POLICY
              value: "Never"