# Generated by Django 3.0.4 on 2020-05-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
