apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    metadata:
      labels:
        context: elasticsearch-pv
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch-pvc