apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres.yaml
  - volumes.yaml

patchesStrategicMerge:
  - search.yaml
  - web.yaml
  - sync-daemon.yaml
  - web-deployment.yaml
  - elasticsearch.yaml
  - scrape.yaml
