apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      volumes:
        - name: models
          hostPath:
            path: /opt/models
      securityContext:
        runAsUser: 0
        fsGroup: 0
      nodeSelector:
        node.kubernetes.io/instance-type: t3.large
