apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
    version: v1
spec:
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          resources:
            requests:
              memory: 0Mi