import os

TASK_LOGGING_DB_FLUSH_SECONDS = 60
TASK_LAUNCHER_LOCAL = True

SEARCH_MODELS_HOST_PATH = None
RESOURCES_HOST_PATH = None

TASK_IMAGE_PULL_POLICY = os.getenv("TASK_IMAGE_PULL_POLICY", "Always")
TASK_DELETE_SUCCESSFUL_PODS = False
TASK_DELETE_FAILED_PODS = False
