# Generated by Django 3.0.5 on 2020-04-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='classification.Category'),
        ),
    ]
