apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrape-cron
spec:
  schedule: "50 */2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scrape
              image: scrape
              command: ["bash","-c"]
              args: ["export PYTHONPATH=/app:$PYTHONPATH && python run_task.py -u cron scrape"]
              envFrom:
                - secretRef:
                    name: scrape-latest
                - secretRef:
                    name: shared-latest
              volumeMounts:
                - name: resources
                  mountPath: /resources
                - name: models
                  mountPath: /models
          restartPolicy: Never
          volumes:
            - name: resources
              hostPath:
                path: /opt/resources
            - name: models
              hostPath:
                path: /opt/models