apiVersion: batch/v1
kind: Job
metadata:
  name: scrape
spec:
  template:
    spec:
      containers:
        - name: scrape
          image: localhost:32000/scrape:0.0.0
          command: ["bash","-c"]
          args: ["echo Test"]
          envFrom:
            - secretRef:
                name: scrape
      restartPolicy: Never
  backoffLimit: 0