apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  template:
    spec:
      containers:
        - name: web
          image: localhost:32000/web:0.0.0
          imagePullPolicy: Always
          command: ["bash","-c"]
          args: ["echo Running on: $RDS_HOSTNAME && python manage.py migrate && python manage.py loaddata db-202003292022 topics"]
          envFrom:
            - secretRef:
                name: web
            - secretRef:
                name: shared
      restartPolicy: Never
  backoffLimit: 0