apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
        - name: web
          image: web
          command: ["bash","-c"]
          args: ["echo Running on: $RDS_HOSTNAME && python manage.py migrate"]
          envFrom:
            - secretRef:
                name: web
            - secretRef:
                name: shared
      restartPolicy: Never
  backoffLimit: 0