apiVersion: batch/v1
kind: Job
metadata:
  name: superuser
spec:
  template:
    spec:
      containers:
        - name: web
          image: web
          command: ["bash","-c"]
          args: ["export PYTHONPATH=/app:$PYTHONPATH && python scripts/create_superuser.py"]
          envFrom:
            - secretRef:
                name: web
            - secretRef:
                name: shared
      restartPolicy: Never
  backoffLimit: 0