apiVersion: batch/v1
kind: Job
metadata:
  name: pubmed-cleanup
spec:
  template:
    spec:
      containers:
        - name: web
          image: web
          command: ["bash","-c"]
          args: ["export PYTHONPATH=/app:$PYTHONPATH && python scripts/delete_publishing_date_none.py && python scripts/delete_orphaned_records.py"]
          envFrom:
            - secretRef:
                name: web
            - secretRef:
                name: shared
      restartPolicy: Never
  backoffLimit: 0