apiVersion: batch/v1
kind: Job
metadata:
  name: non-english-papers-init
spec:
  template:
    spec:
      containers:
        - name: web
          image: web
          command: ["bash","-c"]
          args: ["export PYTHONPATH=/app:$PYTHONPATH && python manage.py loaddata initial_non_english_papers && python scripts/delete_ignored_papers.py"]
          envFrom:
            - secretRef:
                name: web
            - secretRef:
                name: shared
      restartPolicy: Never
  backoffLimit: 0