apiVersion: batch/v1
kind: Job
metadata:
  name: change-category-colors
spec:
  template:
    spec:
      containers:
        - name: web
          image: web
          command: ["bash","-c"]
          args: ["export PYTHONPATH=/app:$PYTHONPATH && python manage.py loaddata lit-covid-categories"]
          envFrom:
            - secretRef:
                name: web
            - secretRef:
                name: shared
      restartPolicy: Never
  backoffLimit: 0