apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - web-deployment.yaml
  - web-service.yaml
  - job-migrate.yaml
  - search-deployment.yaml
  - search-service.yaml
  - job-dbinit.yaml
  - job-superuser.yaml
  - sync-daemon.yaml
  - job-check-migrations.yaml
  - cronjob-scrape.yaml
  - permissions.yaml
  - job-author-cleanup.yaml
  - job-pubmed-cleanup.yaml
  - job-litcovid-init.yaml
  - job-locations-init.yaml
  - elasticsearch.yaml
  - job-elasticsearch-setup-index.yaml
  - job-non-english-papers-init.yaml
  - job-ingest-topics.yaml
  - job-change-category-colors.yaml
  - cronjob-altmetric-update.yaml
  - job-fix-manually-modified.yaml
  - metrics.yaml
  - job-set-vectorized.yaml