apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - web-deployment.yaml
  - web-service.yaml
  - job-migrate.yaml
  - search-deployment.yaml
  - search-service.yaml
  - job-dbinit.yaml
  - job-superuser.yaml
  - sync-daemon.yaml
  - job-check-migrations.yaml
  - cronjob-scrape.yaml
  - permissions.yaml
  - job-author-cleanup.yaml
  - job-pubmed-cleanup.yaml