apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collabovid-role
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - "deployments"
      - "events"
      - "jobs"
    verbs:
      - "create"
      - "get"
      - "list"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collabovid-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collabovid-role
subjects:
  - kind: ServiceAccount
    name: collabovid-sa
