apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: search
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - secretRef:
                name: shared
            - secretRef:
                name: search
          volumeMounts:
            - name: models
              mountPath: /models
          startupProbe:
            httpGet:
              path: /status
              port: http
            failureThreshold: 80
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: http
            periodSeconds: 10
            initialDelaySeconds: 5
      volumes:
        - name: models
          hostPath:
            path: /models
