apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: search
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 3000Mi
          envFrom:
            - secretRef:
                name: shared
            - secretRef:
                name: search
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: models
              mountPath: /models
            - name: resources
              mountPath: /resources
          startupProbe:
            httpGet:
              path: /status
              port: http
            failureThreshold: 80
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              port: http
            periodSeconds: 10
            initialDelaySeconds: 5
          securityContext:
            runAsUser: 0
      volumes:
        - name: models
          hostPath:
            path: /models
        - name: resources
          hostPath:
            path: /opt/resources
