apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sync-daemon
spec:
  selector:
    matchLabels:
      app: sync-daemon
  template:
    metadata:
      labels:
        app: sync-daemon
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: daemon-set
          image: sync-daemon
          volumeMounts:
            - name: models
              mountPath: /models
            - name: resources
            mountPath: /resources
          envFrom:
            - secretRef:
                name: daemon
            - secretRef:
                name: shared
      terminationGracePeriodSeconds: 5
      volumes:
        - name: models
          hostPath:
            path: /.docker/collabovid-data/models
        - name: resources
            hostPath:
              path: /.docker/collabovid-data/resources