apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: web
          resources:
            requests:
              memory: 500Mi
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: shared
            - secretRef:
                name: web
      serviceAccountName: collabovid-sa