apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres.yaml
  - s3.yaml

secretGenerator:
  - name: web
    envs:
      - web.env
  - name: search
    envs:
      - search.env
  - name: daemon
    envs:
      - daemon.env
  - name: shared
    envs:
      - shared.env
generatorOptions:
  disableNameSuffixHash: true
