apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  labels:
    app: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      volumes:
        - name: vol
          hostPath:
            path: /usr/local/kubedata/s3storage
      containers:
        - name: s3
          image: adobe/s3mock
          ports:
            - containerPort: 9090
          env:
            - name: root
              value: /s3
          volumeMounts:
            - name: vol
              mountPath: /s3
          securityContext:
            runAsUser: 0


---

apiVersion: v1
kind: Service
metadata:
  name: s3
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30002
      protocol: TCP
  selector:
    app: s3

